"use client";

type Trade = {
  type: string;
  timestamp: string;
  price: number;
  shares: number;
  entry_price?: number;
  pnl?: number;
  return_percent?: number;
};

type Props = {
  trades: Trade[];
};

export default function TradeHistory({
  trades,
}: Props) {
  return (
    <section className="overflow-hidden rounded-xl border border-white/[0.06] bg-zinc-900/60">
      <div className="border-b border-white/[0.06] px-5 py-4">
        <h2 className="text-base font-semibold text-white">
          Trade History
        </h2>

        <p className="mt-1 text-xs text-zinc-500">
          Simulated entries and exits generated by
          the selected strategy.
        </p>
      </div>

      <div className="overflow-x-auto">
        <table className="w-full text-sm">
          <thead>
            <tr className="border-b border-white/[0.06] text-xs text-zinc-500">
              <th className="px-5 py-3 text-left">
                Type
              </th>

              <th className="px-5 py-3 text-left">
                Date
              </th>

              <th className="px-5 py-3 text-right">
                Price
              </th>

              <th className="px-5 py-3 text-right">
                Shares
              </th>

              <th className="px-5 py-3 text-right">
                P&L
              </th>

              <th className="px-5 py-3 text-right">
                Return
              </th>
            </tr>
          </thead>

          <tbody>
            {trades.map((trade, index) => {
              const pnl = trade.pnl ?? 0;
              const returnPercent =
                trade.return_percent ?? 0;

              return (
                <tr
                  key={`${trade.timestamp}-${index}`}
                  className="border-b border-white/[0.05] last:border-0"
                >
                  <td className="px-5 py-4">
                    <span
                      className={
                        trade.type === "BUY"
                          ? "font-medium text-blue-400"
                          : "font-medium text-orange-400"
                      }
                    >
                      {trade.type}
                    </span>
                  </td>

                  <td className="px-5 py-4 text-zinc-400">
                    {new Date(
                      trade.timestamp
                    ).toLocaleDateString("id-ID")}
                  </td>

                  <td className="px-5 py-4 text-right text-zinc-300">
                    Rp{" "}
                    {trade.price.toLocaleString(
                      "id-ID"
                    )}
                  </td>

                  <td className="px-5 py-4 text-right text-zinc-400">
                    {trade.shares.toLocaleString(
                      "id-ID"
                    )}
                  </td>

                  <td
                    className={`px-5 py-4 text-right ${
                      pnl > 0
                        ? "text-emerald-400"
                        : pnl < 0
                        ? "text-rose-400"
                        : "text-zinc-400"
                    }`}
                  >
                    {trade.type === "SELL"
                      ? `Rp ${pnl.toLocaleString(
                          "id-ID"
                        )}`
                      : "-"}
                  </td>

                  <td
                    className={`px-5 py-4 text-right ${
                      returnPercent > 0
                        ? "text-emerald-400"
                        : returnPercent < 0
                        ? "text-rose-400"
                        : "text-zinc-400"
                    }`}
                  >
                    {trade.type === "SELL"
                      ? `${returnPercent > 0 ? "+" : ""}${returnPercent.toFixed(
                          2
                        )}%`
                      : "-"}
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>
    </section>
  );
}